language: node_js

notifications:
    email:
        - yiminghe@gmail.com

node_js:
  - 0.10

before_script:
  - npm start &
  - npm test

script:
  - phantomjs --version
  - node tools/test/gen-tc-for-phantom
  - phantomjs tools/test/jasmine-phantomjs.js